export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';

export const GET_DATA_LOADING = 'GET_DATA_LOADING';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILED = 'GET_DATA_FAILED';

export const GET_POKEMON_DETAILS_LOADING = 'GET_POKEMON_DETAILS_LOADING';
export const GET_POKEMON_DETAILS_SUCCESS = 'GET_POKEMON_DETAILS_SUCCESS';
export const GET_POKEMON_DETAILS_FAILED = 'GET_POKEMON_DETAILS_FAILED';

export const COMPARE_POKEMON_LOADING = 'COMPARE_POKEMON_LOADING';
export const COMPARE_POKEMON_SUCCESS = 'COMPARE_POKEMON_SUCCESS';
export const COMPARE_POKEMON_FAILED = 'COMPARISION_DATA_FAILED';